sonar.projectKey=skillsync
sonar.projectName=skillsync
sonar.sources=auth-service/src/main/java
sonar.host.url=http://localhost:9000
sonar.token=sqp_1d7d1cbddac15e4c02bd8103d1bd1ad8d1bd3a12
sonar.java.binaries=.